mysql:
  restart: always
  image: mysql:latest
  environment:
    - MYSQL_USER=mattermost
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=mattermost
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - /srv/docker/mattermost/mysql:/var/lib/mysql

mattermost:
  restart: always
  image: jostyee/docker-mattermost:4.9.0
  links:
    - mysql:mysql
  ports:
    - "8080:80"
  environment:
    - MM_SERVICESETTINGS_LISTENADDRESS=:80
    - MM_SERVICESETTINGS_ENABLECUSTOMEMOJI=true
    - MM_SERVICESETTINGS_ENABLELINKPREVIEWS=true
    - MM_EMAILSETTINGS_INVITESALT=long-and-random-alphanumeric-string
    - MM_FILESETTINGS_PUBLICLINKSALT=long-and-random-alphanumeric-string
    - MM_SQLSETTINGS_ATRESTENCRYPTKEY=long-and-random-alphanumeric-string
    - MM_SQLSETTINGS_DRIVERNAME=mysql
    - MM_SQLSETTINGS_DATASOURCE=user:passwd@tcp(host:port)/db?charset=utf8mb4,utf8%26readTimeout=30s%26writeTimeout=30s
  volumes:
    - /srv/docker/mattermost/mattermost:/opt/mattermost/data

nginx:
  restart: always
  image: nginx:stable-alpine
  links:
    - mattermost:mattermost
  ports:
   - "8080:80"
   - "8443:443"
  environment:
    - NGINX_HOST=www.example.com
  volumes:
    - /srv/docker/mattermost/nginx/mattermost.template:/etc/nginx/conf.d/mattermost.template
    - /srv/docker/mattermost/nginx/mattermost.crt:/etc/nginx/mattermost.crt
    - /srv/docker/mattermost/nginx/mattermost.key:/etc/nginx/mattermost.key
    - /srv/docker/mattermost/nginx/dhparam.pem:/etc/nginx/dhparam.pem
  command: /bin/sh -c "envsubst '$$MATTERMOST_PORT_80_TCP_ADDR:$$NGINX_HOST'
                       < /etc/nginx/conf.d/mattermost.template
                       > /etc/nginx/conf.d/default.conf
                       && nginx -g 'daemon off;'"
